### PR TITLE
Feat/tarla

### PR DESCRIPTION
**Pull request by Amadrath**
EPICS integration finished.

### CODE REVIEW

**Comment by mhier** [comment]
Please cleanup your commit history. We should not rely on squash-merging, since it is error prone (you only see what you get when it's too late). Even if you want one single commit, squash them on the branch already, please, and give it a proper title (e.g. "feat: TARLA with EPICS") - although it looks like you need multiple commits...

For the future, I recommend relying on fixup commits to avoid inventing commit messages which won't be visible in the end anyway. The first commit of something big will then already get the message of the final commit (ideally at least - you can always "reword" later), even though it does not yet do what it claims. Further work is committed as fixup commits ("git commit --fixup <id>" - I have a nice configuration for tig to simplify this if you are interested) on that initial commit and finally gets squashed via "git rebase origin/master -i --autosquash". In the end, this often is actually less work :-)

Btw: A good commit message states primarily why something has changed, and only secondary where the change was (since that is visible in the commit itself anyway). So titles like "chore(config): Updated db/req-files" are less helpful then e.g. "fix(config): Corrected error in start script", although it would be better to state what error is fixed. In both cases though the "(config)" is redundant, since the entire repository is for the config. You might rephrase the second message into "fix(start script): path of save&restore files", just as an example...

**Comment by Amadrath** [comment]
As requested, I cleaned up the commits. It was not possible, to merge https://github.com/ChimeraTK/StepperMotor-config/pull/11/commits/e694bfef4d1632027bef66d682fac529642c1576 into the previous commits, as it contains changes in all parts of the configuration.
I add the (config) tag, because this config uses the project template, and this way it is easier to distinguish commits from the template with those from the configuration itself.

**Comment by mhier** [comment]
> I add the (config) tag, because this config uses the project template, and this way it is easier to distinguish commits from the template with those from the configuration itself.

The project template uses "(project-template)" as a tag, and this is strictly enforced now by the distribution script.

Also there should be nothing titled "wip" in the master (even though these are not your commits)...

Finally, it would be very helpful if corrections done within the branch (later commit correct mistakes done in earlier commits of the branch) are squashed into the earlier commits. This helps a lot, also when generating the release notes. I know it's difficult to do this at such a late stage, but please do it as much as possible, it will also help to refine the workflow for next time :-)

**Comment by phako** [comment]
I'd possibly squash everything from 85b741a4a5b2bf1d15af089cda058295c28e8368 to 2e261db073bd166b497fbe1b5be3566a783ae91a into a single commit "Add initial Tarla configuration" and what Martin already mentioned, there is no need for the (config) suffix here.

**Review by phako — APPROVED** [review]
See other comment

**Pull request merged**
